In [17]:
import torch
import torch.nn as nn

# dice
Dice = torch.Tensor([0]).float().cuda()
input = torch.eye(3)
target = torch.zeros(3,3)
smooth = 0.01
# print(target)

intersect=(input*target).sum()
union = torch.sum(input) + torch.sum(target)
Dice=(2*intersect+smooth)/(union+smooth)
dice_loss=1-Dice
print(dice_loss)

tensor(0.9967)


In [ ]:
#TODO conv
import torch.nn as nn

class A:
    def __init__(self):
        self.a = 1

class unetConv2(nn.Module):
    def __init__(self,in_size,out_size,is_batchnorm,n=2,ks=3,stride=1,padding=1):
        super(unetConv2, self).__init__()
        self.n = n
        self.ks = ks # kernel_size
        self.stride = stride
        self.padding = padding
        s = stride
        p = padding
        if is_batchnorm:
            for i in range(1,n+1):
                conv = nn.Sequential(nn.Conv2d(in_size,out_size,ks,s,p),
                                     nn.BatchNorm2d(out_size),
                                     nn.ReLU(inplace=True))
                setattr(self,'conv%d'%i,conv)
                in_size = out_size
        
        else:
            for i in range(1,n+1):
                conv = nn.Sequential(nn.Conv2d(in_size,out_size,ks,s,p),
                                     nn.ReLU(inplace=True))
                setattr(self,'conv%d'%i,conv)
                in_size = out_size

if __name__ == "__main__":
    # a = A()
    # setattr(a,'b',2)
    # print(getattr(a,'a'))
    # print(getattr(a,'b'))
    unet = unetConv2(1,64,True)
    print(unet)


In [43]:
import torch
import torch.nn as nn

input = torch.arange(1, 5, dtype=torch.float32).view(1, 1, 2, 2)
up = nn.ConvTranspose2d(1,2,2,2,0)
print(input)
print(up(input))
up1 = nn.Sequential(nn.UpsamplingBilinear2d(scale_factor=2),
                    nn.Conv2d(1, 2, 1))
print(up1(input))

tensor([[[[1., 2.],
          [3., 4.]]]])
tensor([[[[-0.0933, -0.1346,  0.1454,  0.0630],
          [-0.4698, -0.1300, -0.6076,  0.0720],
          [ 0.3842,  0.2606,  0.6230,  0.4581],
          [-0.7453,  0.2741, -0.8830,  0.4762]],

         [[ 0.2584, -0.1945,  0.4830, -0.4227],
          [-0.2184,  0.1690, -0.4707,  0.3042],
          [ 0.7076, -0.6510,  0.9322, -0.8793],
          [-0.7229,  0.4393, -0.9752,  0.5745]]]],
       grad_fn=<SlowConvTranspose2DBackward>)
tensor([[[[ 0.5904,  0.7073,  0.8242,  0.9411],
          [ 0.8242,  0.9411,  1.0580,  1.1749],
          [ 1.0580,  1.1749,  1.2918,  1.4087],
          [ 1.2918,  1.4087,  1.5256,  1.6425]],

         [[-1.3160, -1.6264, -1.9369, -2.2473],
          [-1.9369, -2.2473, -2.5578, -2.8682],
          [-2.5578, -2.8682, -3.1787, -3.4891],
          [-3.1787, -3.4891, -3.7996, -4.1100]]]],
       grad_fn=<ThnnConv2DBackward>)
