In [ ]:
import torch

a = torch.arange(9).view(3,3)
print("a =",a)
print("a.view(9) =",a.view(9))
print("a.stride() =",a.stride())
c = a.permute(1,0)
print("c =",c)
print("c.stride() =",c.stride())
c.reshape(9)

In [ ]:
#TODO np

import random
import numpy as np
import torch

num_time_steps =50
start = random.randint(0,2)
time_steps = np.linspace(start, start + 10, num_time_steps)
data = np.sin(time_steps)
data = data.reshape(num_time_steps,1)
x = torch.tensor(data[:-1]).float().view(1, num_time_steps - 1, 1)
y = torch.tensor(data[1:]).float().view(1, num_time_steps - 1, 1)

In [11]:
# TODO np.reshape
import numpy as np
a= np.arange(0,9).reshape(3,3)
print(a.shape)
a = np.reshape(a,(1,)+a.shape)
print(a.shape)

(3, 3)
(1, 3, 3)


In [21]:
# TODO np.stack
import numpy as np
a = np.arange(0,3)
b = np.stack(a)

print(a)
print(b)

[0 1 2]
[0 1 2]


In [29]:
import torch

a = torch.rand(3,4)
print(a)
b = torch.round(a).byte().cuda()
print(b.data.cpu())

tensor([[0.1970, 0.9014, 0.7884, 0.0510],
        [0.2792, 0.1846, 0.4352, 0.4418],
        [0.9428, 0.8679, 0.2734, 0.3272]])
tensor([[0, 1, 1, 0],
        [0, 0, 0, 0],
        [1, 1, 0, 0]], dtype=torch.uint8)


In [2]:
def test():
    a = 0
    if(a>0):
        b=a
    else:
        b=10
    return b

x = test()
print(x)

10


In [1]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])
print(np.equal(a,b))

[[ True  True  True]
 [ True  True  True]]


In [3]:
a = [(1,2,3),(2,3,4)],[(1)]
print(a[0][0][0])

1
